// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG_6emtgcDvJOX_LD_JcSjGwTveZOB8wI',
    appId: '1:25619813036:web:7b125b0f0632e77eff4509',
    messagingSenderId: '25619813036',
    projectId: 'feschat-4655',
    authDomain: 'feschat-4655.firebaseapp.com',
    storageBucket: 'feschat-4655.firebasestorage.app',
    measurementId: 'G-JK94FYHJKB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxxgeO1YJrWRY48DOY54F166Gjj5VcKNQ',
    appId: '1:25619813036:android:67aa3288cb6f790eff4509',
    messagingSenderId: '25619813036',
    projectId: 'feschat-4655',
    storageBucket: 'feschat-4655.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnKMedWDSwMgE9qktD-uoBvNE9FvBXpRk',
    appId: '1:25619813036:ios:04e6727a6a398f7eff4509',
    messagingSenderId: '25619813036',
    projectId: 'feschat-4655',
    storageBucket: 'feschat-4655.firebasestorage.app',
    iosBundleId: 'com.example.fesChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnKMedWDSwMgE9qktD-uoBvNE9FvBXpRk',
    appId: '1:25619813036:ios:04e6727a6a398f7eff4509',
    messagingSenderId: '25619813036',
    projectId: 'feschat-4655',
    storageBucket: 'feschat-4655.firebasestorage.app',
    iosBundleId: 'com.example.fesChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCG_6emtgcDvJOX_LD_JcSjGwTveZOB8wI',
    appId: '1:25619813036:web:4d0fb6b3fae06289ff4509',
    messagingSenderId: '25619813036',
    projectId: 'feschat-4655',
    authDomain: 'feschat-4655.firebaseapp.com',
    storageBucket: 'feschat-4655.firebasestorage.app',
    measurementId: 'G-XS5ZKDBK14',
  );
}
